-- 1) member:34240854

DELETE FROM  BILLING  where TRANSACTION_ID=84464060 AND SUBSCRIPTION_PLAN_ID =89366433;

UPDATE STRIPE_PAYMENT_METHOD SET STATUS = 'UNKNOWN' WHERE CUSTOMER_ID ='cus_Qph4F0JcDstwU4' AND ID = 1212236;

UPDATE MEMBER SET TRANSACTION_ID = 84464060 WHERE ID = 34240854 AND TRANSACTION_ID = NULL;

UPDATE PAYER_PAYMENT_PROFILE SET STATUS = 'UNKNOWN' WHERE MEMBER_ID = 34240854;

-- Verification Query should return one
--  SELECT 1 as EXPECTED, COUNT(*) as ACTUAL FROM BILLING b WHERE b.TRANSACTION_ID = 84464060 AND b.SUBSCRIPTION_PLAN_ID = 89366433;
EXECUTE CompareExpectedActual @sqlQuery = N'SELECT 0 as EXPECTED, COUNT(*) as ACTUAL FROM BILLING b WHERE b.TRANSACTION_ID = 84464060 AND b.SUBSCRIPTION_PLAN_ID = 89366433;';

-- Verification Query should return ACTIVE  

--  SELECT 'ACTIVE' as EXPECTED, spm.STATUS ACTUAL FROM STRIPE_PAYMENT_METHOD spm WHERE spm.CUSTOMER_ID = 'cus_Qph4F0JcDstwU4' AND ID = 1212236;


-- Verification Query should return NULL  

--  SELECT 'NULL' as EXPECTED, m.TRANSACTION_ID ACTUAL FROM MEMBER m WHERE m.ID = 34240854;


-- Verification Query should return ACTIVE  

--  SELECT 'ACTIVE' as EXPECTED, ppp.STATUS ACTUAL FROM PAYER_PAYMENT_PROFILE ppp WHERE ppp.MEMBER_ID = 34240854;


